#!/bin/bash

TABMAPPER_PATH="F:/research/software/code/eclipse/""tabmapper/"

DATA_IN=$TABMAPPER_PATH"data/in/"
DATA_IN_TAB=$TABMAPPER_PATH"data/in/tab/"
DATA_IN_MIDI=$TABMAPPER_PATH"data/in/MIDI/"
DATA_OUT=$TABMAPPER_PATH"data/out/"

# 2. Create data folders
if [ ! -d $DATA_IN ]; then
    mkdir -p $DATA_IN
fi

if [ ! -d $DATA_IN_TAB ]; then
    mkdir -p $DATA_IN_TAB
fi

if [ ! -d $DATA_IN_MIDI ]; then
    mkdir -p $DATA_IN_MIDI
fi

if [ ! -d $DATA_OUT ]; then
    mkdir -p $DATA_OUT
fi

#echo $CODE_PATH"cp.sh"

# 3. Call java with the arguments given to tabmapper
# NB. This command can also be called directly from the CLI
java -cp $($TABMAPPER_PATH"cp.sh") tabmapper.TabMapper $1 $2 $3