#!/bin/bash

# Script that runs TabMapper.

code_path="F:/research/software/code/eclipse/"
tabmapper_path="$code_path""tabmapper/"

# Call java with the arguments given to tabmapper
# NB. This command can also be called directly from the CLI
java -cp $("$tabmapper_path""cp.sh") tabmapper.TabMapper $1 $2 $3